ChemFH/urls.py
from django.contrib import admin
from django.urls import path, include
from .api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('services/', include('service.urls')),
    path("api/", api.urls),
]

home/urls.py
# -*- coding: utf-8 -*-
"""
ChemFH was developed by Jiacai Yi et al. of CBDD GROUP of CSU China.
This project is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
Based on a work at http://home.scbdd.com.
Permissions beyond the scope of this license may be available at http://home.scbdd.com/. If you have any questions, please feel free to contact us.

# @Time    : 2020/10/22 下午6:46
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""

from django.urls import path, re_path

from . import views
from django.views.generic import TemplateView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('documentation/', views.documentation, name="documentation"),
    path('documentation/<str:path>/', views.documentationPath, name="documentationpath"),
    path('publication/', views.publication, name="publication"),
    path('apis/', views.apis, name="apis"),
    # path('apis/<str:path>/', views.apispath, name="apispath"),
]

service/urls.py
# -*- coding: utf-8 -*-
"""
ChemFH was developed by Jiacai Yi et al. of CBDD GROUP of CSU China.
This project is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
Based on a work at http://home.scbdd.com.
Permissions beyond the scope of this license may be available at http://home.scbdd.com/. If you have any questions, please feel free to contact us.

# @Time    : 2020/10/22 下午10:14
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""
from django.urls import path

from . import views

app_name = 'service'
urlpatterns = [
    path('evaluation/index/', views.evaluationIndex, name="evaluation"),
    path('evaluation/cal', views.evaluationCal, name="evaluationCal"),
    path('screening/index/', views.filterIndex, name="screening"),
    path('screening/cal', views.screeningCal, name="filterCal"),
    path('screening-result/', views.screening_result, name="screening_result"),
    path('screening/<str:filename>/<int:index>', views.screening_detail, name="screening_detail"),
    path('result-datasource/', views.datasource, name="result_datasource"),
    path('result/<str:filename>', views.result_file, name='result'),
    path('downpdf', views.downloadPDF, name="downpdf"),
    path('downcsv', views.downloadCSV, name="downcsv"),
    path('download', views.download, name="download"),
]

service/models.py
from django.db import models


# Create your models here.

class chemfh(models.Model):
    taskid = models.CharField(db_column='taskId', max_length=255, primary_key=True)
    smiles = models.TextField(blank=True, null=True)
    aggregators = models.FloatField(db_column='Aggregators', blank=True, null=True)
    fluc = models.FloatField(db_column='FLuc inhibitors', blank=True, null=True)
    blue = models.FloatField(db_column='Blue fluorescence', blank=True, null=True)
    green = models.FloatField(db_column='Green fluorescence', blank=True, null=True)
    reactive = models.FloatField(db_column='Reactive compounds', blank=True, null=True)
    other = models.FloatField(db_column='Other assay interference', blank=True, null=True)
    promiscuous = models.FloatField(db_column='Promiscuous compounds', blank=True, null=True)
    aggregators_un = models.FloatField(db_column='Aggregators uncertainty', blank=True, null=True)
    fluc_un = models.FloatField(db_column='FLuc inhibitors uncertainty', blank=True, null=True)
    blue_un = models.FloatField(db_column='Blue fluorescence uncertainty', blank=True, null=True)
    green_un = models.FloatField(db_column='Green fluorescence uncertainty', blank=True, null=True)
    reactive_un = models.FloatField(db_column='Reactive compounds uncertainty', blank=True, null=True)
    other_un = models.FloatField(db_column='Other assay interference uncertainty', blank=True, null=True)
    promiscuous_un = models.FloatField(db_column='Promiscuous compounds uncertainty', blank=True, null=True)
    aggregators_idx = models.TextField(db_column='Aggregators_index', blank=True, null=True)
    fluc_idx = models.TextField(db_column='Fluc_index', blank=True, null=True)
    blue_idx = models.TextField(db_column='Blue_fluorescence_index', blank=True, null=True)
    green_idx = models.TextField(db_column='Green_fluorescence_index', blank=True, null=True)
    reactive_idx = models.TextField(db_column='Reactive_index', blank=True, null=True)
    other_idx = models.TextField(db_column='Other_assay_interference_index', blank=True, null=True)
    promiscuous_idx = models.TextField(db_column='Promiscuous_index', blank=True, null=True)
    alarm = models.TextField(db_column='ALARM_NMR_index', blank=True, null=True)
    bms = models.TextField(db_column='BMS_index', blank=True, null=True)
    chelator = models.TextField(db_column='Chelator_Rule_index', blank=True, null=True)
    gst = models.TextField(db_column='GST_FHs_Rule_index', blank=True, null=True)
    his = models.TextField(db_column='His_FHs_Rule_index', blank=True, null=True)
    luciferase = models.TextField(db_column='Luciferase_Inhibitor_Rule_index', blank=True, null=True)
    ntd = models.TextField(db_column='NTD_index', blank=True, null=True)
    pains = models.TextField(db_column='PAINS_index', blank=True, null=True)
    potential = models.TextField(db_column='Potential_Electrophilic_Rule_index', blank=True, null=True)
    lilly = models.TextField(db_column='Lilly_index', blank=True, null=True)

    class Meta:
        db_table = 'chemfh'

service/forms.py
# -*- coding: utf-8 -*-
"""
ChemFH was developed by Jiacai Yi et al. of CBDD GROUP of CSU China.
This project is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
Based on a work at http://home.scbdd.com.
Permissions beyond the scope of this license may be available at http://home.scbdd.com/. If you have any questions, please feel free to contact us.

# @Time    : 2020/10/23 下午1:51
# @Author  : Jiacai Yi
# @FileName: forms.py
# @E-mail  ：1076365758@qq.com
"""
from django import forms
from django.contrib.auth.models import User
import re

mechanism_choices = (
    ("0", "colloidal aggregators"),
    ("1", "Fluc inhibitors"),
    ("2", "blue fluorescence"),
    ("3", "green fluorescence"),
    ("4", "reactive compounds"),
    ("5", "other assay interferences"),
    ("6", "promiscuous compounds"),
)


class EvaluationSingleForm(forms.Form):
    smiles = forms.CharField(label="SMILES", required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control form-control-lg',
        }
    ), help_text='Please enter a valid SMILES!')
    method = forms.CharField(label='method', initial='1', widget=forms.HiddenInput(attrs={}))
    mechanism = forms.MultipleChoiceField(label="Mechanism", choices=mechanism_choices,
                                          widget=forms.CheckboxSelectMultiple(
                                              attrs={
                                                  'class': 'list-unstyled',
                                              }
                                          ))

service/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import tempfile
import time
import os
import math
from django.conf import settings
import pandas as pd
import numpy as np
from django.http import FileResponse
from rdkit.Chem import PandasTools as pt
import json
from random import randrange
from django.http import HttpResponse

from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import rdDepictor

import static.media.rule.filter_rule as fr
from rdkit.Chem import Draw
import base64
from io import BytesIO

from service.utils.handle_pdf import gen_pdf


def HighlightAtoms(mol, highlightAtoms, figsize=[400, 200], kekulize=True):
    """This function is used for showing which part of fragment matched the SMARTS by the id of atoms.

    :param mol: The molecule to be visualized
    :type mol: rdkit.Chem.rdchem.Mol
    :param highlightAtoms: The atoms to be highlighted
    :type highlightAtoms: tuple
    :param figsize: The resolution ratio of figure
    :type figsize: list
    :return: a figure with highlighted molecule
    :rtype: IPython.core.display.SVG

    """

    def _revised(svg_words):
        """
        """
        svg_words = svg_words.replace(
            'stroke-width:2px', 'stroke-width:1.5px').replace(
            'fonts-size:17px', 'fonts-size:15px').replace(
            'stroke-linecap:butt', 'stroke-linecap:square').replace(
            'fill:#FFFFFF', 'fill:none').replace(
            'svg:', '')
        return svg_words

    mc = Chem.Mol(mol.ToBinary())

    if kekulize:
        try:
            Chem.Kekulize(mc)
        except:
            mc = Chem.Mol(mol.ToBinary())
    if not mc.GetNumConformers():
        rdDepictor.Compute2DCoords(mc)
    drawer = rdMolDraw2D.MolDraw2DSVG(*figsize)
    drawer.DrawMolecule(mc, highlightAtoms=highlightAtoms)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    # It seems that the svg renderer used doesn't quite hit the spec.
    # Here are some fixes to make it work in the notebook, although I think
    # the underlying issue needs to be resolved at the generation step
    return _revised(svg)


un_threhold = [
    0.0010918042703688,
    0.004291940348845,
    0.0009872382265281,
    0.0023240092127062,
    0.0016870113071982,
    0.0061948686233965,
    9.781904685012926e-05,
]

all_rule = ['Aggregators', 'Fluc', 'Blue_fluorescence', 'Green_fluorescence', 'Reactive', 'Other_assay_interference',
            'Promiscuous', 'ALARM_NMR', 'BMS', 'Chelator_Rule', 'GST_FHs_Rule', 'His_FHs_Rule',
            'Luciferase_Inhibitor_Rule', 'NTD', 'PAINS', 'Potential_Electrophilic_Rule', 'Lilly']
from rdkit import Chem
from rdkit import RDConfig
from rdkit.Chem import AllChem as Chem
from rdkit.Chem import Descriptors, Lipinski, QED
from rdkit.Chem.Scaffolds import MurckoScaffold
from math import pi, log10
from collections.abc import Iterable
from itertools import combinations


def evaluationIndex(request):
    return render(request, "services/evaluation/index.html", {})


def filterIndex(request):
    return render(request, "services/screening/index.html")


from service.utils.utils import getMD5
from .models import chemfh

name2dbName = {
    'id': 'id', 'taskid': 'taskId', 'smiles': 'smiles', 'aggregators': 'Colloidal aggregators',
    'fluc': 'FLuc inhibitors',
    'blue': 'Blue fluorescence',
    'green': 'Green fluorescence', 'reactive': 'Reactive compounds', 'other': 'Other assay interference',
    'promiscuous': 'Promiscuous compounds', 'aggregators_un': 'Colloidal aggregators uncertainty',
    'fluc_un': 'FLuc inhibitors uncertainty', 'blue_un': 'Blue fluorescence uncertainty',
    'green_un': 'Green fluorescence uncertainty', 'reactive_un': 'Reactive compounds uncertainty',
    'other_un': 'Other assay interference uncertainty', 'promiscuous_un': 'Promiscuous compounds uncertainty',
    'aggregators_idx': 'Aggregators_index',
    'fluc_idx': 'Fluc_index', 'blue_idx': 'Blue_fluorescence_index', 'green_idx': 'Green_fluorescence_index',
    'reactive_idx': 'Reactive_index',
    'other_idx': 'Other_assay_interference_index', 'promiscuous_idx': 'Promiscuous_index',
    'alarm': 'ALARM_NMR_index', 'bms': 'BMS_index', 'chelator': 'Chelator_Rule_index',
    'gst': 'GST_FHs_Rule_index', 'his': 'His_FHs_Rule_index',
    'luciferase': 'Luciferase_Inhibitor_Rule_index', 'ntd': 'NTD_index', 'pains': 'PAINS_index',
    'potential': 'Potential_Electrophilic_Rule_index', 'lilly': 'Lilly_index'
}

dbName2name = {v: k for k, v in name2dbName.items()}

other_rule_explanation = [
    'Thiol reactive compounds;<br/> 75 substructures <br/>J Am Chem Soc 2005;127:217–24',
    'Undesirable, reactive compounds;<br/> 176 substructures <br/>J Chem Inf Model 2006;46:1060–8',
    'Chelators;<br/> 55 substructures <br/>ChemMedChem 2010;5:195–9',
    'GST/GSH FHs;<br/> 34 substructures <br/>J Biomol Screen 2016;21:596–607',
    'Ni2+ chelators;<br/> 19 substructures <br/>J Biomol Screen 2014;19:715–26',
    'FLuc inhibitors;<br/> 3 substructures <br/>J Chem Inf Model 2018;58:933–42',
    'Unwanted groups, reactive groups and possible HTS interferences;<br/> 105 substructures <br/>ChemMedChem '
    '2008;3:435–44',
    'Frequent hitters, Alpha-screen artifacts and reactive compound;<br/> 480 substructures <br/>J Med Chem '
    '2010;53:2719–40',
    'Reactive compounds;<br/> 119 substructures <br/>J Chem Inf Model 2012;52:2310–6',
    'Interfere with biological assays; <br/> 273 substructures <br/>J Med Chem 2012;55:9763-9772'
]

mechanism_explanation = [
    'Category 0: Non-aggregators; Category 1: aggregators. <br/>The output value is the probability of being '
    'aggregators, within the range of 0 to 1.',
    'Firefly luciferase (FLuc) inhibitors. Category 0: Non-FLuc inhibitors; Category 1: FLuc inhibitors. '
    '<br/>The output value is the probability of being FLuc inhibitors, within the range of 0 to 1.',
    'Category 0: Non-fluorescence; Category 1: fluorescence. <br/>The output value is the probability of being '
    'fluorescence, within the range of 0 to 1.',
    'Category 0: Non-fluorescence; Category 1: fluorescence. <br/>The output value is the probability of being '
    'fluorescence, within the range of 0 to 1.',
    'Category 0: Non-reactive; Category 1: reactive.<br/> The output value is the probability of being '
    'reactive compounds, within the range of 0 to 1.',
    'Category 0: Non-promiscuous; Category 1: promiscuous. <br/>The output value is the probability of being '
    'promiscuous, within the range of 0 to 1.',
    'Category 0: Non-assay interferences; Category 1: assay interferences. <br/>The output value is the probability '
    'of being assay interferences, within the range of 0 to 1.'
]

other_rule_display = ['ALARM NMR Rule', 'BMS Rule', 'Chelator Rule', 'GST FHs Rule',
                      'His FHs Rule', 'Luciferase Inhibitor Rule', 'NTD Rule', 'PAINS Rule',
                      'Potential Electrophilic Rule', 'Lilly Medchem Rules']


def evaluationCal(request):
    score_level = 'High Risk'
    if request.method == 'POST':
        message = ''
        method = request.POST.get('method')
        if method == '1':
            smiles = request.POST.get('smiles')
        else:
            smiles = str(request.POST.get('mol'))
        if not smiles:
            message = 'The SMILES is invalid! please check!'
            return render(request, 'services/evaluation/index.html', locals())
        structure = ''
        mol = Chem.MolFromSmiles(smiles)
        if not mol:  # mol为空，说明输入的SMILES字符串是错误的
            message = 'The SMILES is invalid! please check!'
            tab_choice = 'input'
            return render(request, 'services/evaluation/index.html', locals())

        token = getMD5(smiles)
        task = chemfh.objects.filter(taskid=token).exists()
        t = token
        if task:
            # 表示该smiles存在数据库
            result = chemfh.objects.get(taskid=token)
            data = {field: value for field, value in result.__dict__.items() if not field.startswith('_')}
            df = pd.DataFrame([data])
            result = df.rename(columns=name2dbName)
        else:
            from static.media.chemprop.scripts.predict import predict
            result, unResult = predict([smiles])
            result = result.round(3)
            out1, out2, out3, out4 = fr.filter_rule([smiles], all_rule)
            smiles_df = pd.DataFrame([smiles], columns=['smiles'])
            result = pd.concat([smiles_df, result, unResult, out4], axis=1)
            # 保存进数据库
            task_id = pd.DataFrame([t], columns=['taskId'])
            result = pd.concat([task_id, result], axis=1)
            save_result = result.rename(columns=dbName2name)
            chemfh.objects.create(
                **(save_result.to_dict(orient="records")[0]))
        structure = HighlightAtoms(mol, highlightAtoms=(), figsize=[400, 400])
        mechanisms_name = ['Colloidal aggregators', 'FLuc inhibitors',
                           'Blue fluorescence', 'Green fluorescence', 'Reactive compounds', 'Promiscuous compounds',
                           'Other assay interference', ]
        uncertainty_name = [item + ' uncertainty' for item in mechanisms_name]
        score_list = result[mechanisms_name].iloc[0]
        score_result = score_list.transpose().reset_index()
        score_result.columns = ['mechanism', 'score']
        uncertainty_list = result[uncertainty_name].iloc[0].values.tolist()
        score_result['uncertainty'] = [item < un_threhold[_] for _, item in enumerate(uncertainty_list)]
        return_result = score_result

        def func_decision(row):
            if row['score'] > 0.5:
                return False
            else:
                return True

        return_result['decision'] = return_result.apply(func_decision, axis=1)

templates/services/detail_content.html
{% load static %}
<link rel="stylesheet" href="{% static 'services/css/result_style.css' %}"/>
<link rel="stylesheet" href="{% static 'common/DataTables/DataTables-1.13.8/css/jquery.dataTables.css' %}">
<link rel="stylesheet" href="{% static 'services/css/style.css' %}">
{#<link rel="stylesheet" href="{% static 'common/DataTables/Buttons-2.4.2/css/buttons.dataTables.min.css' %}">#}

{#<script src="{% static 'common/DataTables/pdfmake-0.2.7/pdfmake.js' %}"></script>#}
{#<script src="{% static 'common/DataTables/pdfmake-0.2.7/vfs_fonts.js' %}"></script>#}

<script src="{% static 'common/DataTables/DataTables-1.13.8/js/jquery.dataTables.js' %}"></script>
{#<script src="{% static 'common/DataTables/Buttons-2.4.2/js/dataTables.buttons.js' %}"></script>#}
{#<script src="{% static 'common/DataTables/Buttons-2.4.2/js/buttons.html5.js' %}"></script>#}
{#<script src="{% static 'services/js/echarts.min.js' %}"></script>#}
<script src="{% static 'services/chartjs/chart.umd.js' %}"></script>
<div class="main-content container-xl mt-2">
    <div class="p-3" role="alert" style="word-break:break-all;border: 1px solid rgb(44,63,88)">
        <div class="py-3 d-flex align-items-center justify-content-between">
            <div>
                <span class="d-flex align-items-center" style="font-weight: 600">{{ smiles }} <button
                        class="structure-btn btn ms-4" data-bs-toggle="modal" data-bs-target="#exampleModal">2D
                    structure</button></span>
                <div class="modal fade" id="exampleModal" tabindex="-1"
                     aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog  d-flex justify-content-center align-items-center"
                         style="height: 100%">
                        <div class="modal-content">
                            <div class="modal-body text-center">
                                {{ structure|safe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if download %}
                <div>
                    <a href="javascript:void(0);" style="text-decoration: none;" class="" id="download_csv">
                        <button type="button" class="btn btn-outline-success">
                            <i class="fas fa-download"></i>
                            Download as CSV
                        </button>
                    </a>
                    <a href="javascript:void(0);" style="text-decoration: none;" class="" id="download_pdf">
                        <button type="button" class="btn btn-outline-danger">
                            <i class="fas fa-download"></i>
                            Download as PDF
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="resultPage mt-2" id="resultPage">
        <div class="row gx-3 gy-2 mb-1 mt-2">
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xl-8">
                <canvas id="main" class="pe-5" style="max-height: 100%"></canvas>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <div class="sub-title" style="">Frequent Hitter Rules</div>
                <table class="table table-bordered table-hover table-striped" id="ruleTable">
                    <tbody>
                    {% for _, item in other_rules.iterrows %}
                        <tr>
                            <td>{{ item.mechanism }}</td>
                            <td class="text-center">{{ item.cnt_match }}</td>
                            <td class="text-center">
                                {% if item.cnt_match != 0 %}
                                    <i class="fas fa-exclamation-triangle"
                                       data-tippy-content="click to see the alerts structure" style="color:red"
                                       data-bs-toggle="modal" data-bs-target="#rule-{{ forloop.counter0 }}"></i>

                                    <div class="modal fade" id="rule-{{ forloop.counter0 }}" tabindex="-1"
                                         aria-labelledby="exampleModal2Label" aria-hidden="true">
                                        <div class="modal-dialog modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h1 class="modal-title fs-5" id="exampleModal2Label">Structure
                                                        View</h1>
                                                </div>
                                                <div class="modal-body text-center">
                                                    {{ item.img_match|safe }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <i class="fas fa-info-circle" data-tippy-content="{{ item.explanation }}"></i>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="sub-title mb-3">Frequent Hitter Mechanisms</div>
        <table id="myTable" class="display mb-3">
            <thead>
            <tr>
                <th>Mechanisms</th>
                <th class="text-center">Pred. Score</th>
                <th class="text-center">Decision</th>
                {#                <th class="text-center">Attention</th>#}
                <th class="text-center">Uncertainty</th>
                <th class="text-center">Num. of Substructure</th>
                <th class="text-center">Substructure</th>
                {#                <th class="text-center"></th>#}
            </tr>
            </thead>
            <tbody>
            {% for _, item in result.iterrows %}
                <tr>
                    <td>
                        {{ item.mechanism }} <i class="fas fa-info-circle"
                                                data-tippy-content="{{ item.explanation }}"></i>
                    </td>
                    <td class="text-center">
                        {{ item.score|floatformat:3 }}
                    </td>
                    <td class="text-center">
                        {% if item.decision %}
                            <i class="fas fa-circle text-success"></i>
                        {% else %}
                            <i class="fas fa-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if item.uncertainty %}
                            <span class="badge rounded-pill" style="background-color: #79A1FB">High-confidence</span>
                        {% else %}
                            <span class="badge rounded-pill" style="background-color: #F07875">Low-confidence</span>
                        {% endif %}
                    </td>
                    <td class="text-center">{{ item.cnt }}</td>
                    <td class="text-center">
                        {% if item.cnt != 0 %}
                            <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal-{{ forloop.counter0 }}">View
                            </button>
                        {% else %}
                            -
                        {% endif %}
                        <div class="modal fade" id="exampleModal-{{ forloop.counter0 }}" tabindex="-1"
                             aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        {{ item.svg|safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    {#                    <td class="text-center">#}
                    {#                        <i class="fas fa-info-circle" data-tippy-content="{{ item.explanation }}"></i>#}
                    {#                    </td>#}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="alert alert-primary mb-3" type="info"
         style="font-size: 1.1rem;font-family: 'Poppins',serif;">
        <p style="font-size: 1.2rem;" class="mb-0">
            <i class="fas fa-info-circle"></i> Tips:
        </p>
        <ul class="m-0">
            <li>
                The corresponding relationships of the two labels are as follows: <i class="fas fa-circle
                text-success"></i> <span
                    class="text-success">Pass</span> (Non-FH compound);
                <i class="fas fa-circle text-danger"></i> <span class="text-danger">Reject</span> (FH compound)
            </li>
        </ul>
    </div>
</div>

<div class="modal" tabindex="-1" id="loading-btn">
    <div class="modal-dialog d-flex justify-content-center align-items-center" style="height: 100%;">
        <div class="modal-content" style="background: none; border: none;">
            <div class="modal-body text-center" style="border: none;">
                <div class="load">
                    <hr/>
                    <hr/>
                    <hr/>
                    <hr/>
                </div>
                <h2 style="color: white">Please Wait...</h2></div>
        </div>
    </div>
</div>
<script src="{% static 'common/js/popper.min.js' %}"></script>
<script src="{% static 'common/js/tippy-bundle.umd.min.js' %}"></script>

<script>
    tippy('[data-tippy-content]', {
        maxWidth: 'none',
        role: 'tooltip',
        allowHTML: true,
    });

    function randerChart() {
        {#Chart.defaults.font.size = 16;#}
        const ctx = document.getElementById('main');
        let labels = {{ mechanisms|safe }};
        let values = {{ score|safe }};
        const data = {
            labels: labels,
            datasets: [
                {
                    label: 'Predicted Score',
                    data: values,
                    borderColor: '#416F9D',
                    backgroundColor: 'rgba(66,78,104, 0.1)',
                    pointRadius: 5,
                },
            ]
        };
        Chart.defaults.borderColor = '#2C3F58';
        new Chart(ctx, {
            type: 'radar',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        display: false
                    },
                },
                scales: {
                    r: {
                        beginAtZero: false, //從 0 開始計算
                        max: 1, //最大數值
                        ticks: {
                            stepSize: 0.2,
                        },
                        pointLabels: {
                            color: '#000',
                            font: {
                                size: 16,
                            },
                        },
                    }
                }
            },
        });
    }

    $(document).ready(function () {
        randerChart();
        $('#myTable').DataTable({
            dom: 'Bfrtip',
            paging: false,
            ordering: false,
            searching: false,
            info: false,
            {#buttons: [#}
            {#    'copyHtml5',#}
            {#    'csvHtml5',#}
            {#    'pdfHtml5',#}
            {#]#}
        });

    });

    $('#download_csv').click(function () {
        $.ajax({
            type: "POST",
            url: "{% url 'service:downcsv' %}",
            data: {'taskid': "{{ taskid }}"},
            beforeSend: function (xhr, setting) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
            },
            success: function (result) {
                var blob = new Blob([result]);
                var link = document.createElement('a');
                link.href = window.URL.createObjectURL(blob);
                link.download = "ChemFH_result.csv";
                link.click();
            },
            error: function (result) {
            }
        });
    })

    const myModal = new bootstrap.Modal('#loading-btn', {
        keyboard: false,
        backdrop: 'static',
    })

    function showmodal() {
        myModal.show()
    }

    function closemodal() {
        myModal.hide()
    }

    $('#download_pdf').click(function () {
        showmodal();
        $.ajax({
            type: "POST",
            url: "{% url 'service:downpdf' %}",
            data: {'taskid': "{{ taskid }}"},
            beforeSend: function (xhr, setting) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
            },
            success: function (result) {
                var blob = new Blob([result]);
                var link = document.createElement('a');
                link.href = window.URL.createObjectURL(blob);
                link.download = "ChemFH_result.pdf";
                link.click();
                closemodal();
            },
            error: function (result) {
            }
        });
    });
</script>