ChemFH/urls.py
from django.contrib import admin
from django.urls import path, include
from .api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('services/', include('service.urls')),
    path("api/", api.urls),
]

home/urls.py
# -*- coding: utf-8 -*-
"""
ChemFH was developed by Jiacai Yi et al. of CBDD GROUP of CSU China.
This project is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
Based on a work at http://home.scbdd.com.
Permissions beyond the scope of this license may be available at http://home.scbdd.com/. If you have any questions, please feel free to contact us.

# @Time    : 2020/10/22 下午6:46
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""

from django.urls import path, re_path

from . import views
from django.views.generic import TemplateView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('documentation/', views.documentation, name="documentation"),
    path('documentation/<str:path>/', views.documentationPath, name="documentationpath"),
    path('publication/', views.publication, name="publication"),
    path('apis/', views.apis, name="apis"),
    # path('apis/<str:path>/', views.apispath, name="apispath"),
]

service/urls.py
# -*- coding: utf-8 -*-
"""
ChemFH was developed by Jiacai Yi et al. of CBDD GROUP of CSU China.
This project is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
Based on a work at http://home.scbdd.com.
Permissions beyond the scope of this license may be available at http://home.scbdd.com/. If you have any questions, please feel free to contact us.

# @Time    : 2020/10/22 下午10:14
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""
from django.urls import path

from . import views

app_name = 'service'
urlpatterns = [
    path('evaluation/index/', views.evaluationIndex, name="evaluation"),
    path('evaluation/cal', views.evaluationCal, name="evaluationCal"),
    path('screening/index/', views.filterIndex, name="screening"),
    path('screening/cal', views.screeningCal, name="filterCal"),
    path('screening-result/', views.screening_result, name="screening_result"),
    path('screening/<str:filename>/<int:index>', views.screening_detail, name="screening_detail"),
    path('result-datasource/', views.datasource, name="result_datasource"),
    path('result/<str:filename>', views.result_file, name='result'),
    path('downpdf', views.downloadPDF, name="downpdf"),
    path('downcsv', views.downloadCSV, name="downcsv"),
    path('download', views.download, name="download"),
]

templates/common/banner.html
{% load static %}

<style>
    .pre-link {
        color: white;
        text-decoration: underline;
    }

    .pre-link:hover {
        color: orange;
    }
</style>

<div class="jumbotron jumbotron-fluid pt-0" style="background-color: rgba(42,64,88)">
    <div class="container" style="width: 86%" id="banner-container-fluid">
        <div class="row d-flex justify-content-around align-items-center" style="height: 100%">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 pl-4 pr-4" id="container-right"
                 style="color: #fff; font-weight: 700; font-size: 1.25rem">
                <h1 class="fw-bolder text-center mb-3" style="font-size: 48px; color: #d2e0ed">ChemFH</h1>
                <p class="lead" style="text-align: justify; font-weight: 350; line-height: 2rem; font-size: 1.1rem;
                font-family: 'Raleway', sans-serif">
                    In early drug discovery, detecting frequent false positives poses a significant challenge, leading
                    to wasted time and resources in hit identification. To address this, <a
                        href="#">ChemFH</a> (Chemical Frequent
                    Hitter), an integrated online platform, predicts potential frequent hitters across various
                    parameters. Utilizing high-quality database and Directed Message Passing Neural Network (DMPNN)
                    architectures, ChemFH enhances the efficiency of drug R&D by achieving reliable detection of
                    frequent hitters in colloidal aggregate, firefly luciferase reporter enzyme inhibition,
                    fluorescence, chemical reactivity, and promiscuity.
                </p>
                <div class="text-center">
                    <a href="{% url 'home:documentation' %}" class="button button-primary learn-more mb-2"
                       style="text-decoration: none">Learn
                        More</a>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 text-center d-flex justify-content-center
            align-items-center my-5"
                 id="container-left"
                 style="">
                <img src="{% static 'home/img/homepage.png' %}" alt="" class="img-fluid" style="width: 86%"/>
            </div>
        </div>
    </div>
</div>

templates/common/base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>ChemFH</title>
    <script src="{% static 'common/js/jquery.min.js' %}"></script>

    {# nav.html #}
    {% block navres %}
        <link rel="stylesheet" type="text/css" href="{% static 'common/nav/css/style.css' %}"/>
        <script src="{% static 'common/nav/js/style.js' %}"></script>
    {% endblock %}

{#    <link href="{% static 'common/css/bootstrap.min.css' %}" rel="stylesheet"/>#}
{#    <script src="{% static 'common/js/bootstrap.bundle.min.js' %}"></script>#}
    <link rel="stylesheet" href="{% static 'common/bootstrap-5.3.2-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'common/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'home/css/scroll_style.css' %}">

    {# footer.html #}
    <link rel="stylesheet" href="{% static 'common/footer/css/style.css' %}"/>

    {# banner.html #}
    <link rel="stylesheet" href="{% static 'common/banner/css/style.css' %}"/>

    {# fonts #}
    <link href="{% static 'common/fontawesome/css/all.min.css' %}" rel="stylesheet" type="text/css"/>

</head>
<body>
<div class="antin-container">
    {% block nav %}
        {% include 'common/nav.html' %}
    {% endblock %}

    {% block banner %}
        {% include 'common/banner.html' %}
    {% endblock %}

    <div class="antin-contain">
        {% block content %}

        {% endblock %}
    </div>
    {% block footer %}
        {% include 'common/footer.html' %}
    {% endblock %}
</div>
</body>

{% block script %}

{% endblock %}
</html>

templates/common/footer.html
{% load static %}

<footer class="site-footer">
    <div class="container" id="footer-container">
        <div class="row">
            <div class="col-sm-12 col-md-6 d-flex flex-column">
                <h6>About</h6>
                <p class="text-justify" style="text-align: justify">
                    The website provides a precise and efficient service for identifying frequent hitter compounds. This
                    functionality is based on a high-quality database comprising 810,000 entries across seven distinct frequent hitter mechanisms and employs a multi-task DMPNN model framework.
                </p>
                <p class="copyright-text mt-auto" style="color: #D4E0EC; text-align: justify">
                    We utilize CSRF tokens (Cookies) to safeguard against cross-site request forgery attacks, a vital security measure for our website. We assure you that we respect your privacy and do not store or share any other personal information on your device.
                </p>
            </div>

            <div class="col-xs-6 col-md-3 d-flex flex-column">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li><a href="{% url 'home:contact' %}">Contact Us</a></li>
                    <li><a href="http://www.scbdd.com/" target="_blank">CBDD Group</a></li>
                    <script type="text/javascript"
                            src="//rf.revolvermaps.com/0/0/7.js?i=5m5j0dg4igq&amp;m=0&amp;c=ff0000&amp;cr1=ffffff&amp;br=10&amp;sx=0"
                            async="async"></script>
                </ul>
            </div>
            <div class="col-xs-6 col-md-3 d-flex flex-column">
                <h6>Dev Tool</h6>
                <table class="xtable">
                    <tr>
                        <td>
                            <a href="https://www.python.org/" target="_blank">
                                <img src="{% static 'common/footer/img/python-logo.png' %}" alt="">
                            </a>
                        </td>
                        <td>
                            <a href="https://www.rdkit.org/" target="_blank">
                                <img src="{% static 'common/footer/img/rdkit-logo.png' %}" alt="">
                            </a>
                        </td>
                        {#                        <td>#}
                        {#                            <a href="https://www.djangoproject.com/" target="_blank">#}
                        {#                                <img src="{% static 'common/footer/img/django-logo.png' %}" alt="">#}
                        {#                            </a>#}
                        {#                        </td>#}
                        <td>
                            <a href="https://pytorch.org/" target="_blank">
                                <img src="{% static 'common/footer/img/pytorch-logo.png' %}" alt="">
                            </a>
                        </td>
                        <td>
                            <a href="https://www.rdkit.org/" target="_blank">
                                <img src="{% static 'common/footer/img/djangoninja-logo.png' %}" alt="">
                            </a>
                        </td>
                    </tr>
                    <tr>
                    </tr>
                </table>
                <div class="mt-3 text-end">
                    <p class="copyright-text">
                        E-mail: <font color="white">oriental-cds@163.com</font>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="container" id="footer-container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="text-end">
                    <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
                        <a href="http://www.scbdd.com/" style="color: #ffffff;text-decoration: none">Computational
                            Biology & Drug Design
                            Group</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/common/nav.html
{% load static %}
<style>
    .box-with-border {
        border-bottom: 1px solid #333; /* 边框样式，2px 宽度，颜色 #333 */
        {#padding: 2px; /* 可选：增加一些内边距，使内容不紧贴边框 */#}
    }

    /* 添加阴影 */
    .box-with-shadow {
        box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.3); /* x偏移、y偏移、模糊度、颜色（rgba格式） */
        {#padding: 2px; /* 可选：增加一些内边距，使内容不紧贴阴影 */#}
    }

    .nav-link {
        font-size: 1.1rem;
    }
</style>
<header class="header-area overlay box-with-border box-with-shadow">
    <nav class="navbar navbar-expand-md navbar-dark" data-bs-theme="dark">
        <div class="container">
            <a href="{% url 'home:index' %}" class="navbar-brand d-flex justify-content-center align-items-center">
                <img src="{% static 'favicon.ico' %}" width="45" height="45"
                     class="d-inline-block justify-content-center align-items-center me-2" alt=""/>
                <h1 class="">ChemFH<span>.</span></h1>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav"
                    aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="main-nav" class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}"><i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fas fa-atom"></i> Services
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'service:evaluation' %}">FH Evaluation</a></li>
                            <li><a class="dropdown-item" href="{% url 'service:screening' %}">FH Screening</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:apis' %}"><i class="fas fa-robot"></i> API Tutorial</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:documentation' %}">
                        <i class="fas fa-hands-helping"></i> Documentation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:publication' %}"><i class="fas fa-copy"></i> Publication</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:contact' %}"><i class="fas fa-id-card"></i> Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>